//
//  CardData.swift
//  TrezeCartas
//
//  Created by Evaldo Garcia de Souza Júnior on 10/02/21.
//

import Foundation
import SwiftUI

class CardData {
    
    public func getShuffledCards() -> [Card]{
        var shuffledCards = cards.shuffled()
        for i in 0 ..<  shuffledCards.count {
            shuffledCards[i].id = i
        }
        self.cards = shuffledCards // Colocando caso tenha algum local do código que pegue diretamente de CardData().cards
        return shuffledCards
    }
    
    @State var cards: [Card] = [
        Card(id: 0, cardImage: UIImage(named: "__Sede")!, cardName: "Tá com Sede?", cardText: "Eita, calor tá grande demais. Tu tais lembrando de beber água? Trata de fazer algo que tu não vai aguentar assim.", leftOption: "Beber água", rightOption: "Tirar a camisa", leftAnswer: "Bebeu água, não \n Tá com sede, tô \n Olha, olha, olha, olha a água mineral \n Água mineral \n Água mineral \n Água mineral \n Do Candeal \n Você vai ficar legal", rightAnswer: "Lá vai a biscoiteira tirando a camisa pra chamar atenção dos boys... Mas tu não se lembra de passar o protetor solar nunca, né? Em resumo, ficou todo queimado, desidratou e terminou com uma insolação. Bebe água, menino!", leftStatus: [3, -2, -1], rightStatus: [-3, 0, -3]),
        Card(id: 1, cardImage: UIImage(named: "__Ele_quer")!, cardName: "Será que Ele Quer?", cardText: "Você vai chegar em um boy que estava trocando olhares com você, mas ele fala com jeitinho que não esta a fim. Será que isso é apenas timidez?", leftOption: "Insistir em beijar", rightOption: "Voltar pros amigos", leftAnswer: "Insistir em beijar alguém não é brincadeira de Carnaval, é assédio. Então, aprende a respeitar o espaço do outro e que as pessoas podem não estar a fim. Não é não e ponto final. Vê se deixa de escrotisse no próximo carnaval.", rightAnswer: "Você sabe muito bem que Não é Não. Agora fica tranquilo e continua curtindo teu Carnaval, que ainda tem muita coisa boa pra acontecer. Compra um 3 é 10, chama os amigos e segue o bloco!", leftStatus: [-10, -10, -10], rightStatus: [3, 0, 1]),
        Card(id: 2, cardImage: UIImage(named: "__Pirata")!, cardName: "O Pirata", cardText: "Você olha pro lado e vê um pirata chegando em você. Com tapa olho, bigode enroladinho e uma cara de mal. Eita, olha o tamanho da espada dele... Vai andar na prancha ou vai se entregar ao perigo?", leftOption: "Andar na prancha", rightOption: "AHOY!", leftAnswer: "O pirata parecia perigoso demais e você preferiu pular daquele barco. Agora é esperar outro marujos cairem nos seus encantos de sereia. Mas espera, o que é aquilo ali no chão? Será que o pirata derrubou o fruto da sua pirataria? Achasse 30 reais no chão!", rightAnswer: "O pirata vem e lhe dá um beijão. Você sente ele apalpando todo seu corpo, você fica enlouquecido. Vocês passam um bom tempo se beijando, mas ele sai quase sem falar nada. Espera, não tá sentindo seu bolso leve demais? Amigo, acho que além de roubar seu coração, ele roubou junto a sua carteira...", leftStatus: [0, 2, 0], rightStatus: [-1, -3, 0]),
        Card(id: 3, cardImage: UIImage(named: "__bloco_da_lama")!, cardName: "O Bloco da Lama", cardText: "Eita, olha a galera chegando do bloco da lama. Tá todo mundo coberto de lama dos pés a cabeça. E lá vem uma amiga tua, calma ela está querendo te abraçar?", leftOption: "Abraçar a amiga", rightOption: "Falar de longe", leftAnswer: "Ai, menino, é carnaval, bora se melar também. Afinal, lama não é bom para a pele? Você se abraçam e vc se mela todinho. Eita, mas cadê aquele boyzinho que você estava trocando olhares? Acho que ele correu quando te viu melado. Pelo menos tua pele vai ficar hidratada, né?", rightAnswer: "Sua amiga vem te abraçar, mas vc fala de longe mesmo. Melhor não se melar, né? Ela fala algumas vezes como você é sem graça e que deveria se divertir mais. Por falar em diversão, o boy que estava trocando olhares com você está chegando perto. Que tal se divertir com ele?", leftStatus: [2, 0, -1], rightStatus: [1, 0, 0]),
        Card(id: 4, cardImage: UIImage(named: "__selfie")!, cardName: "Tira uma Selfie", cardText: "Você junta a galera pra tirar aquela selfie com cara de acabado digna de todo bom Carnaval. Todo mundo troncho, rindo um bocado. Agora guarda o celular!", leftOption: "Celular na pochete", rightOption: "Celular na doleira", leftAnswer: "Você guarda o celular na pochete. Mas logo começa um empurra empurra. Vocês correm pro canto. Mas calma, cadê sua pochete? Eita, boy, fosse assaltado. Ainda bem que ainda tens um dinheiro na doleira. Pelo menos conseguisse registrar a foto maravilhosa nos stories.", rightAnswer: "Você guardou o celular na doleira. Você passa tranquilo por todo o empurra empurra, sem medo de ser assaltado. Você segue então brincando e um de seus amigos oferece um drink que acabou de comprar.", leftStatus: [-1, -3, 0], rightStatus: [1, 0, 1]),
        Card(id: 5, cardImage: UIImage(named: "__Escadaria")!, cardName: "A Escadaria", cardText: "Você vê uma amiga sua que faz tempo que não vê lá no alto da escadaria curtindo uma fritação. Corre lá pra falar com ela antes de perder ela de vista.", leftOption: "Enfrentar fila", rightOption: "Enfrentar lama", leftAnswer: "Você tenta subir os caminhos da escadaria, mas eles estão cheio de gente. Com a demora pra conseguir subir, você perde sua amiga de vista. Pra não perder a viagem, você resolve parar em uma das barracas pra lanchar e tomar uma água. Quem sabe vocês não se esbarram em outro carnaval?", rightAnswer: "Você vai pelo caminho mais difícil, mas consegue subir bem mais rápido e chega na sua amiga. Vocês se abraçam, contam as fofocas e aproveitam para poder tomar um latão e f1 juntos. Ela ainda te apresenta um amigo dela, gatinho ele. Vocês trocam uns olhares, ele elogia sua fantasia e acaba saindo um beijão.", leftStatus: [2, -3, -2], rightStatus: [1, 0, 2]),
        Card(id: 6, cardImage: UIImage(named: "__Roda_Beck")!, cardName: "A Roda de Beck", cardText: "Tu vai encontrar aquele contatinho que estava esperando ali no canto da ladeira. De repente, ele puxa dois becks e forma uma roda com os amigos. E aí?", leftOption: "Entrar na roda", rightOption: "Proerd é o programa", leftAnswer: "Ele acende os dois becks e passa cada um pra um lado. Enquanto os becks vão passando, você nota que os dois estão chegando ao mesmo tempo em você. Então é isso, agora vai ter que tragar os dois ao mesmo tempo. Bota um de cada lado da boca e se joga que vai dar bom!", rightAnswer: "De vez em quando, aparece cada amigo na vida da gente. Eles chegam oferecendo drogas. Eles falam que droga é legal só pra você aceitar. Mas que tipo de amigo é esse? É Quando algum desses amigos chegar oferecendo droga, você pega os seus dedinhos e faz assim pras drogas.", leftStatus: [-1, 0, 3], rightStatus: [-2, 0, -3]),
        Card(id: 7, cardImage: UIImage(named: "__Encontro_Blocos")!, cardName: "Encontro de Blocos", cardText: "Você está no meio do aperto da 13 quando ouve o bater de um surdo vindo das suas costas. Mas calma, lá na frente não tá vindo um bloco? Certeza que esses dois blocos vão se esbarrar bem onde você está.", leftOption: "Se imprensar", rightOption: "Esperar os blocos", leftAnswer: "Você se imprensa com o pessoal nas barracas nas beiras da rua. É um empurra empurra danado, mas você aproveita pra comprar uma garrafa de água. Eita, aquele boyzinho tá olhando pra você. Eita, que ele tá vindo. Chegou com uma pala, mas tu já ficasse todo animado. Beija logo e aproveita!", rightAnswer: "Bicha, a senhora é afrontosa, viu? Vai ficar esperando os blocos chegarem? Os blocos chegam, a rua vira uma festa e tu tá bem no meio! Todo mundo se divertindo e vendo você dançar frevo pra se acabar! A festa está toda a sua volta, se joga que Carnaval é pra isso mesmo! Não esquece de beber água depois!", leftStatus: [2, -2, 0], rightStatus: [3, 0, 0]),
        Card(id: 8, cardImage: UIImage(named: "__Cade_Povo")!, cardName: "Eita, Cadê o Povo?", cardText: "Você olha para um lado, olha pro outro e só vê a multidão no empurra empurra. Onde foram parar os teus amigos? E agora, como vai encontrar eles? Vocês marcaram algum ponto de encontro?", leftOption: "Subir a escadaria", rightOption: "Ir pro MAC", leftAnswer: "Você resolve subir a escadaria para poder olhar do alto. Mas tá uma confusão da gota! É gente, é bicho, é barraca, é barranco... Cuidado pra não tropeçar naquele bu... Tarde demais, caísse e se melasse todinho na lama. Agora tais perdido e todo cagado.", rightAnswer: "Como todo ano, tu já sabe, se perdeu corre pro MAC. Você vai se debatendo no meio do povo, se imprensando no meio das filas. De repente, você vê o cabelo colorido do seu amigo. E vê que chique, eles já te recepcionam com loló e água.", leftStatus: [-2, -1, -2], rightStatus: [2, 0, 1]),
        Card(id: 9, cardImage: UIImage(named: "__Aquilo_e_Doce")!, cardName: "Aquilo é um Doce?", cardText: "Tu e teu amigo estão subindo as escadarias quando ele encontra um zip lock largado no chão. Parece que dentro dele tem uns papeizinhos... O que será que pode ser isso?", leftOption: "Colocar na boca", rightOption: "Deixar no chão", leftAnswer: "Ei, ooo que tt acc conte sendo? 4s CoZax tt04 1/2 Ex tttttrrrr ãããããããããã nH4z. EEEiEiiiaifo, vvoou C T4 wW3ell? 4Xho Ki é BbBoOm nN User eSsasSs coooo us4sS 100 Xab3R D1 0nD véio. Eh drègui ihhhhhhhh", rightAnswer: "Talvez você tenha feito a melhor escolha, talvez não... Mas ao menos você está vivo e não usou droga que encontrou no chão. Bom saber a procedência do que você está colocando do seu corpo, não é? Eita, aquele boy tá vendendo beck, corre lá pra comprar!", leftStatus: [-1, 0, 3], rightStatus: [1, -3, 1]),
        Card(id: 10, cardImage: UIImage(named: "__Onde_Fica_Banheiro")!, cardName: "Onde Fica o Banheiro?", cardText: "Eita, que tais doido pra mijar, não é? Corre atrás de um canto logo, que aqueles 3 latões estão doidos pra sair. Mas e aí, onde é que faz xixi no carnaval?", leftOption: "Mijar no beco", rightOption: "Banheiro químico", leftAnswer: "Corresse pro beco, já encontrasse uma vaga e o xixi já tá saindo e escorrendo pelas ladeiras de Olinda. Mas é bom sair do aperto, né? Calma, ali no cantinho é uma nota de 10 reais?", rightAnswer: "Boy, a fila dos banheiros da 13 estão enormes. E os banheiros já estão querendo transbordar... Desse jeito você não vai aguentar, melhor correr e pagar 2 reais pra fazer xixi naquela casa. Lembrando que dois reais é só o número 1, o número 2 é mais caro...", leftStatus: [3, 2, -2], rightStatus: [2, -2, -3]),
        Card(id: 11, cardImage: UIImage(named: "__Diabo_Loiro")!, cardName: "Um Diabo Loiro", cardText: "Um diabo louro faiscou na minha frente/ Com cara de gente, bonito demais/ Chegou de bobeira, marcando zoeira no meio da praça/ Quebrando vidraças, isto não se faz", leftOption: "Foi paranóico", rightOption: "Me fez sedento", leftAnswer: "Será que o boy tá me olhando? Será que eu chego nele? Será que eu tô com muita cara de doido? Será que ele está olhando pra outra pessoa? Que rolê é esse? De onde veio toda essa gente? Acho que você está ficando noiado...", rightAnswer: "Bicha, que boy é esse? Tais doida pra dar uns beijos. Mas calma lá, ele tá beijando uma boyzinha? Eita, ele tá beijando um boyzinho também! Tais sedento pra ser o próximo, né? Mas esse diabo já faiscou novamente e sumiu no meio da multidão. Agora só próximo carnaval.", leftStatus: [-3, -1, 2], rightStatus: [-1, 0, 0]),
        Card(id: 12, cardImage: UIImage(named: "__O_Boy_Magia")!, cardName: "O Boy Magia", cardText: "Você está pulando atrás de um bloco com seus amigos e o seu crush aparece no meio da multidão. Calma, ele está te chamando?", leftOption: "Encontrar o boy", rightOption: "Dar um tchauzinho", leftAnswer: "Você foi até o boy e ele já foi te beijando. PQP, o boy beija bem demais! Mas calma, onde foram parar o bloco e seus amigo? Acho que você se perdeu deles.", rightAnswer: "Você vê o boy acenando de volta, ele parece um pouco desapontado. Mas calma, não se desespere, logo ali o latão é 3 é 10! Bom que já afoga a mágoa com os amigos e segue o bloco.", leftStatus: [-10, 0, 0], rightStatus: [1, -1, 1])
    ]
    
}
